### ISSUE TITLE
No dark mode ?

### ISSUE THREAD

**Issue by pikachuk** [consulo/consulo#376]
- IDE build number:
2355
- Java version:
OpenJDK 1.8.0_232
- OS name and version: 
KDE Neon 5.17

In Intellij Idea, I am able to set the entire UI to dark (the Darkula theme) however in Consulo, there doesn't seem to be an option except for the text editor part 

![image](https://user-images.githubusercontent.com/16335601/70866766-e7424e00-1f6d-11ea-8214-7dee5dffdbbd.png)

**Comment by VISTALL** [comment]
Hello. Settings -> General -> UI -> Theme -> Darcula

**Comment by pikachuk** [comment]
> Hello. Settings -> General -> UI -> Theme -> Darcula

Thanks a lot !
I feel like the option could maybe be made a bit more visible or have a shortcut somewhere because for people coming from Intellij Idea, it's a bit surprising to not find it in the same place

**Comment by VISTALL** [comment]
> Thanks a lot !
I feel like the option could maybe be made a bit more visible or have a shortcut somewhere because for people coming from Intellij Idea, it's a bit surprising to not find it in the same place

Consulo don't have common code with IDEA in this case. I made it more friendly old settings, but it was not current IDEA implementations (because fork too old than new settings)

Moving their settings, i don't want - due we have different strategy for filling them (like project language settings).

**Comment by pikachuk** [comment]
> > Thanks a lot !
> > I feel like the option could maybe be made a bit more visible or have a shortcut somewhere because for people coming from Intellij Idea, it's a bit surprising to not find it in the same place
> 
> Consulo don't have common code with IDEA in this case. I made it more friendly old settings, but it was not current IDEA implementations (because fork too old than new settings)
> 
> Moving their settings, i don't want - due we have different strategy for filling them (like project language settings).

I see, but I didn't talk about moving it, more about adding a shortcut somewhere that directly leads to it

**Comment by VISTALL** [comment]
Maybe. I have too many plans, which not always finished. 😅 

You can create issue which describe problem.
