### ISSUE TITLE
How to run after build?

### ISSUE THREAD

**Issue by zubovm** [consulo/consulo#379]
- IDE build number: current git master
- Java version: 1.8.0_232
- OS name and version: Linux Manjaro 18.1.5

So, it successfully builds  from source after
`mvn package`
- and now what?

README.md says that if I want to run
consulo "from the repository' I can do it using
maven (actually it does not work at the moment
too, but never mind); but if don't then what?

Is there any way to run it as a simple application
using some startup script, or install it somehow
to ~/.local/bin, or may be using some
java some.jar?

I am sorry that I am asking that question here, but
actually it is a bug report: there is no such info
in README.md, and it could complicate things
for anyone who tried to build it from sources.

Actually after some digging I've found some
zip archives in
consulo/distribution/target  folder
(not tar archives as it probably should be 
according to installations-from-binary-guide).

Are they what one needs (probably yes)? Also there is
a jar file there, but it does not run:

`java -jar consulo-bundle-2-SNAPSHOT.jar`
no main manifest attribute, in consulo-bundle-2-SNAPSHOT.jar

Is it a feature, or may be it should be fixed too?

**Comment by VISTALL** [comment]
Hello. Consulo can't run as jar file. You are right about `distribution/target` directory - here you can find full build.

If you open then you can find clean Consulo distribution without access right (it's known "problem", since nobody use it *as is*, at my jenkins i repack it with jre, etc).

*package* it's full build Consulo platform project. If you wanna patch Consulo - you need IDE, better Consulo with Consulo DevKit plugin. Consulo platform repository contains run configuration for run Consulo in few modes - but of course you need Consulo.

Maybe go to https://discuss.consulo.io/ ?
