### ISSUE TITLE
Report to GitHub from IDE Fatal Errors dialog

### ISSUE THREAD

**Issue by clumsy** [consulo/consulo#91]
https://developer.github.com/v3/issues/#create-an-issue

**Comment by VISTALL** [comment]
Yep i known that api. Me already used it when i moved Issue tracker from **youtrack** to **github**.

Crash reports is more chaotic. I dont want spam issues to github issue tracker. Because u cant check for duplication(or obsolete). Next problem - plugins dont known about their **source repos**

Maybe i will create service for it, with button **transfer issue on github**.

**Comment by clumsy** [comment]
Well we can always label them and specify the milestone. I do believe IDE Fatal Errors should be checked.
But more importantly there should not be lots of errors that prevent users from working, even due to 3rd parties - at least not as IDE FATAL Errors.

**Comment by VISTALL** [comment]
We can but, plugins downloaded from build server(last build). For now i cant hold - labeled builds. No support by web part
